apiVersion: v1
kind: Service
metadata:
  name: {{ include "sap.fullname" . }}-agent-worker
  labels:
    {{- include "sap.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-worker
spec:
  type: ClusterIP
  selector:
    {{- include "sap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent-worker
  ports:
    - name: grpc
      port: {{ .Values.agentWorker.grpcPort }}
      targetPort: grpc
